spring.application.name=navi

spring.datasource.url=jdbc:sqlite:${DB_PATH:./data/navi.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=1

spring.jpa.open-in-view=false
